#!/bin/bash

# Arguments.
type_major=$1
type_minor=$2
arg3=$3
arg4=$4
arg5=$5
arg6=$6
#echo $arg3 $arg4 $arg5 $arg6


FILE_NAME="${HOME}/bin/mygrep_conf/myConfig.conf"
HELP_FILE="${HOME}/bin/mygrep_conf/readme"
#echo $FILE_NAME


line=""
# The function used to show line with colors.
function show_line () {
	#echo "show_line"

	if [[ $line =~ \[.*\] ]]; then				#like [BT]
		echo -e "\033[31m$line\033[0m"
	elif [[ $line =~ -.* ]]; then				#like "-opp OppLauncher|OppManager #share one file via bluetooth."
		
		#parse the line begin.
		parse_minor=${line%% *}
		#echo "minor = $parse_minor"
		parse_tag=${line#* }
		parse_tag=${parse_tag%#*}
		#echo "tag = $parse_tag"
		parse_anno=${line##*#}
		#echo "anno = $parse_anno"
		#parse the line end.

		echo -e "\033[31m$parse_minor\033[0m    $parse_tag    \033[34m#$parse_anno\033[0m"
	else										#like "#...(Annotations)"
		echo -e "\033[34m$line\033[0m"
	fi
}


# The function used to show help info.
function show_help () {
	#echo "show help"
	local show=0
	while read line 
	do
		#echo $line
		if [[ $line =~ \[.*\] ]]; then
			if [ $show == 1 ]; then
				show=0
			fi
			if [ $line = "[${type_major}]" ]; then
				show_line
				show=1
			fi
		elif [ $show == 1 ]; then
			show_line
		fi
	done < $FILE_NAME
}



tag_found=""
# The function used to grep with tags found.
function grep_func () {
	#echo "grep func"
	grep --color=auto "$tag_found" $arg3 $arg4 $arg5 $arg6	
	echo -e "\033[31mintegral grep command:\033[0m"
	echo 'grep' " $tag_found $arg3 $arg4 $arg5 $arg6"
}


# The function used to find saved tags and grep.
function grep_by_tag () {
	#echo "grep_by_tag"
	local major_found=0
	local parse_minor=""
	while read line 
	do
		#echo $line
		if [[ $line =~ \[.*\] ]]; then
			if [ $major_found == 1 ]; then
				major_found=0
			fi
			if [ $line = "[${type_major}]" ]; then
				major_found=1
			fi
		elif [ $major_found == 1 ]; then
			parse_minor=${line%% *}
			if [ $type_minor = $parse_minor ]; then
				tag_found=${line#* }
				tag_found=${tag_found%#*}
				break
			fi
		fi
	done < $FILE_NAME
	if [ "$tag_found" == "" ]; then
		echo "tag not found for $type_major $type_minor"
	else
		#echo "tag = $tag_found"
		grep_func
	fi

}




# The main function.
function main () {
	if [ "$type_major" = "--help" ]; then
		cat $HELP_FILE
		return
	else if [ "$type_major" = "-v" ]; then
			echo "1.0.0"
			return
		fi
	fi

	if [ "$type_minor" = "-show" ]
	then
		show_help
	else
		grep_by_tag
	fi
}


# Execute the main function.
main
